/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Goal {
  'id' : string,
  'active' : boolean,
  'name' : string,
  'dailyTargetSessions' : bigint,
}
export interface SessionRecord {
  'duration' : bigint,
  'sessionType' : SessionType,
  'dateString' : string,
  'timestamp' : bigint,
}
export type SessionType = { 'focus' : null } |
  { 'short_break' : null } |
  { 'long_break' : null };
export interface StreakData {
  'lastActiveDate' : string,
  'freezeUsedToday' : boolean,
  'longestStreak' : bigint,
  'freezeBalance' : bigint,
  'currentStreak' : bigint,
}
export interface UserSettings {
  'longBreakDuration' : bigint,
  'longBreakInterval' : bigint,
  'shortBreakDuration' : bigint,
  'focusDuration' : bigint,
}
export interface _SERVICE {
  'addGoal' : ActorMethod<[string, string, bigint], undefined>,
  'clearAllSessions' : ActorMethod<[], undefined>,
  'deleteGoal' : ActorMethod<[string], undefined>,
  'earnFreeze' : ActorMethod<[], undefined>,
  'getAllGoals' : ActorMethod<[], Array<Goal>>,
  'getFreezeBalance' : ActorMethod<[], bigint>,
  'getSessionsByDateRange' : ActorMethod<
    [string, string],
    Array<SessionRecord>
  >,
  'getSettings' : ActorMethod<[], UserSettings>,
  'getStreakData' : ActorMethod<[], StreakData>,
  'logSession' : ActorMethod<[bigint, SessionType, string], bigint>,
  'setSettings' : ActorMethod<[bigint, bigint, bigint, bigint], undefined>,
  'updateGoal' : ActorMethod<[string, string, bigint, boolean], undefined>,
  'updateStreak' : ActorMethod<
    [bigint, bigint, string, bigint, boolean],
    undefined
  >,
  'useFreeze' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];