/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Goal = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'dailyTargetSessions' : IDL.Nat,
});
export const SessionType = IDL.Variant({
  'focus' : IDL.Null,
  'short_break' : IDL.Null,
  'long_break' : IDL.Null,
});
export const SessionRecord = IDL.Record({
  'duration' : IDL.Nat,
  'sessionType' : SessionType,
  'dateString' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserSettings = IDL.Record({
  'longBreakDuration' : IDL.Nat,
  'longBreakInterval' : IDL.Nat,
  'shortBreakDuration' : IDL.Nat,
  'focusDuration' : IDL.Nat,
});
export const StreakData = IDL.Record({
  'lastActiveDate' : IDL.Text,
  'freezeUsedToday' : IDL.Bool,
  'longestStreak' : IDL.Nat,
  'freezeBalance' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addGoal' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'clearAllSessions' : IDL.Func([], [], []),
  'deleteGoal' : IDL.Func([IDL.Text], [], []),
  'earnFreeze' : IDL.Func([], [], []),
  'getAllGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getFreezeBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getSessionsByDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(SessionRecord)],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [UserSettings], ['query']),
  'getStreakData' : IDL.Func([], [StreakData], ['query']),
  'logSession' : IDL.Func([IDL.Nat, SessionType, IDL.Text], [IDL.Int], []),
  'setSettings' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'updateGoal' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Bool], [], []),
  'updateStreak' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'useFreeze' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Goal = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'dailyTargetSessions' : IDL.Nat,
  });
  const SessionType = IDL.Variant({
    'focus' : IDL.Null,
    'short_break' : IDL.Null,
    'long_break' : IDL.Null,
  });
  const SessionRecord = IDL.Record({
    'duration' : IDL.Nat,
    'sessionType' : SessionType,
    'dateString' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserSettings = IDL.Record({
    'longBreakDuration' : IDL.Nat,
    'longBreakInterval' : IDL.Nat,
    'shortBreakDuration' : IDL.Nat,
    'focusDuration' : IDL.Nat,
  });
  const StreakData = IDL.Record({
    'lastActiveDate' : IDL.Text,
    'freezeUsedToday' : IDL.Bool,
    'longestStreak' : IDL.Nat,
    'freezeBalance' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  
  return IDL.Service({
    'addGoal' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'clearAllSessions' : IDL.Func([], [], []),
    'deleteGoal' : IDL.Func([IDL.Text], [], []),
    'earnFreeze' : IDL.Func([], [], []),
    'getAllGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getFreezeBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getSessionsByDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(SessionRecord)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [UserSettings], ['query']),
    'getStreakData' : IDL.Func([], [StreakData], ['query']),
    'logSession' : IDL.Func([IDL.Nat, SessionType, IDL.Text], [IDL.Int], []),
    'setSettings' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'updateGoal' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Bool], [], []),
    'updateStreak' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'useFreeze' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };