/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StreakData {
    lastActiveDate: string;
    freezeUsedToday: boolean;
    longestStreak: bigint;
    freezeBalance: bigint;
    currentStreak: bigint;
}
export interface UserSettings {
    longBreakDuration: bigint;
    longBreakInterval: bigint;
    shortBreakDuration: bigint;
    focusDuration: bigint;
}
export interface Goal {
    id: string;
    active: boolean;
    name: string;
    dailyTargetSessions: bigint;
}
export interface SessionRecord {
    duration: bigint;
    sessionType: SessionType;
    dateString: string;
    timestamp: bigint;
}
export enum SessionType {
    focus = "focus",
    short_break = "short_break",
    long_break = "long_break"
}
export interface backendInterface {
    addGoal(id: string, name: string, dailyTargetSessions: bigint): Promise<void>;
    clearAllSessions(): Promise<void>;
    deleteGoal(id: string): Promise<void>;
    earnFreeze(): Promise<void>;
    getAllGoals(): Promise<Array<Goal>>;
    getFreezeBalance(): Promise<bigint>;
    getSessionsByDateRange(startDate: string, endDate: string): Promise<Array<SessionRecord>>;
    getSettings(): Promise<UserSettings>;
    getStreakData(): Promise<StreakData>;
    logSession(duration: bigint, sessionType: SessionType, dateString: string): Promise<bigint>;
    setSettings(focusDuration: bigint, shortBreakDuration: bigint, longBreakDuration: bigint, longBreakInterval: bigint): Promise<void>;
    updateGoal(id: string, name: string, dailyTargetSessions: bigint, active: boolean): Promise<void>;
    updateStreak(currentStreak: bigint, longestStreak: bigint, lastActiveDate: string, freezeBalance: bigint, freezeUsedToday: boolean): Promise<void>;
    useFreeze(): Promise<void>;
}
import type { SessionRecord as _SessionRecord, SessionType as _SessionType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGoal(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGoal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGoal(arg0, arg1, arg2);
            return result;
        }
    }
    async clearAllSessions(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllSessions();
            return result;
        }
    }
    async deleteGoal(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGoal(arg0);
            return result;
        }
    }
    async earnFreeze(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.earnFreeze();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.earnFreeze();
            return result;
        }
    }
    async getAllGoals(): Promise<Array<Goal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGoals();
            return result;
        }
    }
    async getFreezeBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getFreezeBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFreezeBalance();
            return result;
        }
    }
    async getSessionsByDateRange(arg0: string, arg1: string): Promise<Array<SessionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionsByDateRange(arg0, arg1);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionsByDateRange(arg0, arg1);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<UserSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getStreakData(): Promise<StreakData> {
        if (this.processError) {
            try {
                const result = await this.actor.getStreakData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStreakData();
            return result;
        }
    }
    async logSession(arg0: bigint, arg1: SessionType, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.logSession(arg0, to_candid_SessionType_n6(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logSession(arg0, to_candid_SessionType_n6(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async setSettings(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSettings(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSettings(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateGoal(arg0: string, arg1: string, arg2: bigint, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoal(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoal(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateStreak(arg0: bigint, arg1: bigint, arg2: string, arg3: bigint, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStreak(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStreak(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async useFreeze(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.useFreeze();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.useFreeze();
            return result;
        }
    }
}
function from_candid_SessionRecord_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionRecord): SessionRecord {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_SessionType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionType): SessionType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: bigint;
    sessionType: _SessionType;
    dateString: string;
    timestamp: bigint;
}): {
    duration: bigint;
    sessionType: SessionType;
    dateString: string;
    timestamp: bigint;
} {
    return {
        duration: value.duration,
        sessionType: from_candid_SessionType_n4(_uploadFile, _downloadFile, value.sessionType),
        dateString: value.dateString,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    focus: null;
} | {
    short_break: null;
} | {
    long_break: null;
}): SessionType {
    return "focus" in value ? SessionType.focus : "short_break" in value ? SessionType.short_break : "long_break" in value ? SessionType.long_break : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SessionRecord>): Array<SessionRecord> {
    return value.map((x)=>from_candid_SessionRecord_n2(_uploadFile, _downloadFile, x));
}
function to_candid_SessionType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionType): _SessionType {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionType): {
    focus: null;
} | {
    short_break: null;
} | {
    long_break: null;
} {
    return value == SessionType.focus ? {
        focus: null
    } : value == SessionType.short_break ? {
        short_break: null
    } : value == SessionType.long_break ? {
        long_break: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
